### PR TITLE
Rebuild for xxhash 0.8.2

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Since xxhash defines `run_exports`.

Signed-off-by: Julien Jerphanion <git@jjerphan.xyz>

### CODE REVIEW

**Comment by jjerphan** [comment]
@mariusvniekerk: thank you for maintaining this feedstock.

I am keen on becoming a maintainer if this allows improving the bus factor. :slightly_smiling_face:

**Comment by jjerphan** [comment]
Hi @mariusvniekerk: are you interested in a shared maintenance of this feedstock? :slightly_smiling_face:

**Comment by jjerphan** [comment]
@conda-forge-admin, please add user @jjerphan

**Review by marcelotrevisani — APPROVED** [review]

**Comment by jjerphan** [comment]
Thank you, @marcelotrevisani!

**Pull request merged**
